export const CATBOX_UPDATE_HEIGHT = 'CATBOX_UPDATE_HEIGHT';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const CATS_LOADED = 'CATS_LOADED';
export const CATS_LOADING_FAILED = 'CATS_LOADING_FAILED';
export const FEED_UPDATE_WIDTH = 'FEED_UPDATE_WIDTH';
